### ISSUE TITLE
UDP does not work

### ISSUE THREAD

**Issue by arpit9616** [TekMonksGitHub/sockem#6]
> bug

## Testing conditions:
- Tested using latest code. commit id 65c0926b3bfc0364fe2fd3e1b566033cd4a344f0
- Node v14.16.0

## Test Case:
- Start a UDP Echo server on localhost, port 4444
- Test echo server using `nc -u 127.0.0.1 4444`
  - Works OK.
- Start Sockem server on localhost, port 1080
- Update config in `test/udpClient.js` to match our setup
- Test proxy using `test/udpClient.js`
  - Breaks sockem server. Exits on critical error.

#### Sockem logs:
```json
{"ts":"2021:03:10:15:43:25","level":"info","message":"*************************************"}
{"ts":"2021:03:10:15:43:25","level":"info","message":"*************************************"}
{"ts":"2021:03:10:15:43:25","level":"info","message":"Logging subsystem initialized."}
{"ts":"2021:03:10:15:43:25","level":"info","message":"[stdout] [SOCKS5] Server listening on 0.0.0.0:1080\n"}
{"ts":"2021:03:10:15:43:37","level":"debug","message":"[SOCKS5] [127.0.0.1:47308] Connection received."}
{"ts":"2021:03:10:15:43:37","level":"info","message":"[SOCKS5] [UDP] [127.0.0.1:47308] Created new UDP relay listening on 127.0.0.1:60464."}
{"ts":"2021:03:10:15:43:37","level":"error","message":"RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds\n    at boundsError (internal/buffer.js:81:11)\n    at Buffer.readInt16BE (internal/buffer.js:503:5)\n    at _shouldWeRelay (/home/arpit/Documents/git_repos/sockem/lib/socks5UDP.js:75:59)\n    at Socket.<anonymous> (/home/arpit/Documents/git_repos/sockem/lib/socks5UDP.js:61:77)\n    at Socket.emit (events.js:315:20)\n    at UDP.onMessage [as onmessage] (dgram.js:919:8)"}
{"ts":"2021:03:10:15:43:37","level":"error","message":"EXIT ON CRITICAL ERROR!!!"}
```

#### Stack Trace:
```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:81:11)
    at Buffer.readInt16BE (internal/buffer.js:503:5)
    at _shouldWeRelay (/home/arpit/Documents/git_repos/sockem/lib/socks5UDP.js:75:59)
    at Socket.<anonymous> (/home/arpit/Documents/git_repos/sockem/lib/socks5UDP.js:61:77)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
```
---
Link to echo server -> [arpit9616/echo-server](https://github.com/arpit9616/echo-server)

**Comment by tarunv98** [comment]
@arpit9616 - I'm able to replicate the issue.
@TekMonksGitHub - I'll be taking this issue up.

**Comment by TekMonksGitHub** [comment]
@tarunv98 This is critical so expect ETA by EOW - March 12 2021.
